inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - "vendor/**/*"
    - "db/schema.rb"
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - '**/Gemfile'
    - '.pryrc'

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# ブロック内の文字数宣言を無視
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# ダブルクォート使用を強制させたい
Style/StringLiterals:
  EnforcedStyle: double_quotes

# デフォルトの80文字は少ないと判断
Layout/LineLength:
  Max: 120

# rufoでフォーマットすると、今度はLayout/EndAlignmentに引っかかるのでOFF
Style/MultilineTernaryOperator:
  Enabled: false

# 調べてもよくわからないのでOFF
Lint/AmbiguousBlockAssociation:
  Enabled: false

# ４行までは許してほしい
Style/GuardClause:
  MinBodyLength: 4

# do .. end から更にメソッドチェーンすると見づらいので
# auto-correct せず、自分で修正する
# spec 内は見た目が綺麗になるので許可
Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*"

# 修正するのに時間がかかりそうなので・・
Rails/HelperInstanceVariable:
  Enabled: false

# デフォルト15だときつい
Metrics/AbcSize:
  Max: 22
