# 参考サイト https://kitsune.blog/rails-rubocop

# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

# Railsモード
Rails:
  Enabled: true

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - "vendor/**/*"
    - "db/schema.rb"
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - '**/Gemfile'

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# あとで意味を調べる
# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# ブロック内の文字数宣言を無視
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# ダブルクォート使用を強制させたい
Style/StringLiterals:
  EnforcedStyle: double_quotes

# デフォルトの80文字は少ないと判断
Layout/LineLength:
  Max: 120
